lib: [
  "_build/install/default/lib/repl/META" {"META"}
  "_build/install/default/lib/repl/opam" {"opam"}
  "_build/install/default/lib/repl/repl.a" {"repl.a"}
  "_build/install/default/lib/repl/repl.cma" {"repl.cma"}
  "_build/install/default/lib/repl/repl.cmi" {"repl.cmi"}
  "_build/install/default/lib/repl/repl.cmt" {"repl.cmt"}
  "_build/install/default/lib/repl/repl.cmx" {"repl.cmx"}
  "_build/install/default/lib/repl/repl.cmxa" {"repl.cmxa"}
  "_build/install/default/lib/repl/repl.cmxs" {"repl.cmxs"}
  "_build/install/default/lib/repl/repl.dune" {"repl.dune"}
  "_build/install/default/lib/repl/repl.ml" {"repl.ml"}
]
